#!/usr/bin/env ruby

require 'json'

contents = File.read(ARGV.shift)
config = JSON.parse(contents)
cmd = ""
case config["adapter"]
    when 'mysql2'
        cmd = "mysql "
        cmd += "--host=#{config['host']} "
        cmd += "--port=#{config['port']} "
        cmd += "--user=#{config['username']} "
        cmd += "--password=#{config['password']} "
        cmd += "--database=#{config['database']}"
end
puts cmd
system cmd
